version: "3"

services:
  app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
    networks:
      - todoapp
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - volume-db:/data/db
    networks:
      - todoapp

networks:
  todoapp:
    driver: bridge

volumes:
  volume-db: