version: "3"

services:
  app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./data:/data
    networks:
      - todoapp
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - todoapp

networks:
  todoapp:
    driver: bridge
